<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2012-03-27 12:27:38 **/

$Definition['%1$s created an account for %3$s.'] = '%1$s a créé un compte pour %3$s.';
$Definition['%s and you'] = 'Entre %s et vous';
$Definition['%s comment'] = '%s commentaire';
$Definition['%s comments'] = '%s commentaires';
$Definition['%s message'] = '%s message';
$Definition['%s messages'] = '%s messages';
$Definition['%s New'] = '%s Nouveau';
$Definition['%s new'] = '%s nouveau';
$Definition['%s New Plural'] = '%s nouveaux';

$Definition['<General Error>'] = '<Erreur Générale>';
$Definition['<i class="icon-plus"></i> Start a New Discussion'] = '<i class="icon-plus"></i> Nouvelle Discussion';
$Definition['<label>New comment</label>'] = '<label>Nouveau Commentaire</label>';

$Definition['[%1$s] %2$s'] = '[%1$s] %2$s';
$Definition['[%s] Welcome Aboard!'] = '[%s] vous souhaite la bienvenue';

$Definition['A message has been sent to your email address with password reset instructions.'] = 'Un message a été envoyé à votre adresse e-mail avec les instructions de réinitialisation du mot de passe.';
$Definition['About'] = 'À propos…';
$Definition['Accepted'] = 'Acceptée';

// Activity Messages
$Definition['Activity'] = 'Activité';
$Definition['Activity.Comment'] = 'Commenter';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s a mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.FullHeadline.Somebody'] = '%1$s a mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.FullHeadline.Somebody.You'] = '%1$s %3$s a mentionné dans un %8$s.';
$Definition['Activity.CommentMention.FullHeadline.You'] = '%1$s avez mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.FullHeadline.You.Somebody'] = '%1$s avez mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s a mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline.Somebody'] = '%1$s a mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline.Somebody.You'] = '%1$s %3$s a mentionné dans un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline.You'] = '%1$s avez mentionné %3$s dans un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline.You.Somebody'] = '%1$s avez mentionné %3$s dans un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.He'] = '%1$s a envoyé un message à %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.He.You'] = '%1$s a envoyé un message à %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.Somebody'] = '%1$s a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.Somebody.You'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.You'] = '%1$s avez envoyé un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.You.Somebody'] = '%1$s avez envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.He'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.He.You'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.Somebody'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.Somebody.You'] = '%1$s vous a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.You'] = '%1$s avez envoyé un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline.You.Somebody'] = '%1$s avez envoyé un %8$s.';
$Definition['Activity.Delete'] = '×';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s a commenté %4$s %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline.You'] = '%1$s avez commenté la %8$s de %3$s.';
$Definition['Activity.DiscussionComment.FullHeadline.You.Somebody'] = '%1$s avez commenté la %8$s de %3$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s a commenté %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline.You'] = '%1$s avez commenté la %8$s de %3$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline.You.Somebody'] = '%1$s avez commenté la %8$s de %3$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.FullHeadline.Somebody'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.FullHeadline.Somebody.Somebody'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.FullHeadline.You'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.FullHeadline.You.He'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.FullHeadline.You.Somebody'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline.Somebody'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline.Somebody.Somebody'] = '%1$s a rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline.You'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline.You.He'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline.You.Somebody'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.FullHeadline.Somebody'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.FullHeadline.Somebody.Somebody'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.FullHeadline.Somebody.You'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.FullHeadline.You'] = '%1$s avez créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.FullHeadline.You.Somebody'] = '%1$s avez créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline.Somebody'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline.Somebody.Somebody'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline.Somebody.You'] = '%1$s a créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline.You'] = '%1$s avez créé un compte pour %3$s.';
$Definition['Activity.JoinCreated.ProfileHeadline.You.Somebody'] = '%1$s avez créé un compte pour %3$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.FullHeadline.Somebody'] = '%1$s a accepté l\'invitation de %3$s à devenir membre.';
$Definition['Activity.JoinInvite.FullHeadline.Somebody.You'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.FullHeadline.You'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.FullHeadline.You.Somebody'] = '%1$s avez accepté l\'invitation de %3$s à devenir membre.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.ProfileHeadline.Somebody'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.ProfileHeadline.Somebody.You'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.ProfileHeadline.You'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.JoinInvite.ProfileHeadline.You.Somebody'] = '%1$s a accepté %4$s invitation à devenir membre.';
$Definition['Activity.NewComment.FullHeadline'] = '%1$s a commenté une %8$s.';
$Definition['Activity.NewComment.FullHeadline.You'] = '%1$s avez commenté une %8$s.';
$Definition['Activity.NewComment.FullHeadline.You.Somebody'] = '%1$s avez commenté une %8$s.';
$Definition['Activity.NewComment.ProfileHeadline'] = '%1$s a commenté une %8$s.';
$Definition['Activity.NewComment.ProfileHeadline.You'] = '%1$s avez commenté une %8$s.';
$Definition['Activity.NewComment.ProfileHeadline.You.Somebody'] = '%1$s a commenté une %8$s.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s a ouvert une %8$s.';
$Definition['Activity.NewDiscussion.FullHeadline.You'] = '%1$s avez ouvert une %8$s.';
$Definition['Activity.NewDiscussion.FullHeadline.You.Somebody'] = '%1$s avez ouvert une %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s a ouvert une %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline.You'] = '%1$s avez ouvert une %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline.You.Somebody'] = '%1$s avez ouvert une %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s a changé %6$s photo de profil.';
$Definition['Activity.PictureChange.FullHeadline.You'] = '%1$s avez changé %6$s photo de profil.';
$Definition['Activity.PictureChange.FullHeadline.You.Somebody'] = '%1$s avez changé %6$s photo de profil.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s a changé %6$s photo de profil.';
$Definition['Activity.PictureChange.ProfileHeadline.You'] = '%1$s avez changé %6$s photo de profil.';
$Definition['Activity.PictureChange.ProfileHeadline.You.Somebody'] = '%1$s avez changé la photo de profil de %6$s.';

$Definition['Add'] = 'Ajouter';
$Definition['Add a Comment'] = 'Commenter';
$Definition['Add Comment'] = 'Commenter';
$Definition['Add Message'] = 'Rédiger un message';
$Definition['Add People to this Conversation'] = 'Ajouter des personnes…';
$Definition['All Categories'] = 'Toutes les Catégories';
$Definition['All Discussions'] = 'Toutes les Discussions';
$Definition['Allow other members to see your email?'] = 'Autoriser les autres membres à voir mon adresse email ?';
$Definition['Announce'] = 'Annoncer';
$Definition['Announcement'] = 'Annonce';
$Definition['Apply'] = 'Appliquer';
$Definition['Apply for Membership'] = 'Devenir membre';
$Definition['Are you sure you want to do that?'] = 'Êtes-vous sûr de vouloir faire cela ?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = 'Revenir aux Discussions';
$Definition['Bookmark'] = 'Ajouter aux favoris';
$Definition['Bookmarked Discussions'] = 'Discussions Favorites';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'En téléchargeant un fichier, vous certifiez que vous avez les autorisations nécessaires de distribuer cette image et que cela n\'est pas contraire aux Conditions d\'Utilisation de la communauté.';

$Definition['Cancel'] = 'Annuler';
$Definition['Categories'] = 'Catégories';
$Definition['CategoriesShowFollowed'] = 'Afficher uniquement les catégories que vous suivez.';
$Definition['CategoriesShowUnfollowed'] = 'Afficher les catégories non suivies';
$Definition['CategoriesViewingAll'] = 'Toutes les catégories sont affichées.';
$Definition['CategoriesViewingFollowed'] = 'Seules les catégories que vous suivez sont actuellement visibles.';
$Definition['Category'] = 'Catégorie';
$Definition['Category Management'] = 'Gestion des Catégories';
$Definition['Change My Password'] = 'Modifier mon Mot de passe';
$Definition['Change My Picture'] = 'Modifier ma Photo de profil';
$Definition['Change Password'] = 'Modifier le Mot de passe';
$Definition['Change Picture'] = 'Modifier la Photo de Profil';
$Definition['Close'] = 'Fermer';
$Definition['Closed'] = 'Fermée';
$Definition['Comment'] = 'Commenter';
$Definition['comment'] = 'commentaire';
$Definition['Comment by %s'] = 'Commenté par %s';
$Definition['Commenting not allowed.'] = 'Vous n\'êtes pas autorisé à publier des commentaires.';
$Definition['Comments'] = 'Commentaires';
$Definition['Confirm'] = 'Confirmer';
$Definition['Confirm Password'] = 'Confirmez votre Mot de passe';
$Definition['Conversations'] = 'Conversations';
$Definition['Couldn\'t find an account associated with that email/username.'] = 'Impossible de trouver un compte associé à cet e-mail ou à ce nom d\'utilisateur.';
$Definition['Create One.'] = 'Je m\'inscris';

$Definition['Dashboard'] = 'Tableau de bord';
$Definition['Date.DefaultDateTimeFormat'] = '%c';
$Definition['Date.DefaultDayFormat'] = '%e %B';
$Definition['Date.DefaultTimeFormat'] = '%k:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Supprimer';
$Definition['Delete Account'] = 'Supprimer le Compte';
$Definition['Delete Conversation'] = 'Supprimer la Conversation';
$Definition['Delete Discussion'] = 'Supprimer la Discussion';
$Definition['discussion'] = 'discussion';
$Definition['Discussion Title'] = 'Titre de la Discussion';
$Definition['Discussions'] = 'Discussions';
$Definition['Dismiss'] = 'Rejeter';
$Definition['Don\'t have an account? %s'] = 'Pas encore inscrit ? %s';
$Definition['dot'] = 'dot';
$Definition['Draft.Delete'] = '×';
$Definition['Draft saved at %s'] = 'Brouillon enregistré à %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Faites glisser et redimensionnez le carré sur l\'image ci-dessous pour définir votre miniature.';

$Definition['Edit'] = 'Modifier';
$Definition['Edit Account'] = 'Modifier le Compte';
$Definition['Edit Discussion'] = 'Modifier la Discussion';
$Definition['Edit My Account'] = 'Paramètres du Compte';
$Definition['Edit My Thumbnail'] = 'Modifier ma Miniature';
$Definition['Edit Preferences'] = 'Paramètres de notification';
$Definition['Edit Thumbnail'] = 'Modifier la Miniature';
$Definition['Email'] = 'Email';
$Definition['Email/Username'] = 'Email / Nom d\'Utilisateur';
$Definition['Email Unavailable'] = 'Cette adresse email est déjà utilisée par une autre personne.';
$Definition['Enregistrer les Préférences'] = 'Enregistrer les Préférences';
$Definition['Enter the email address of the person you would like to invite:'] = 'Entrez l\'adresse email de la personne que vous souhaitez inviter :';
$Definition['Enter your Email address or username'] = 'Entrez votre adresse email<br />ou votre nom d\'utilisateur';
$Definition['Enter your email address or username'] = 'Entrez votre adresse email<br />ou votre nom d\'utilisateur';
$Definition['ErrorBadInvitationCode'] = 'Code d\'Invitation incorrect';

$Definition['Failed to authenticate your password reset request. Try using the reset request form again.'] = 'Échec de l\'authentification de votre demande de réinitialisation de mot de passe. Essayez d\'utiliser le formulaire de demande de réinitialisation à nouveau.';
$Definition['Female'] = 'Femme';
$Definition['Forgot?'] = '<br />Mot de passe oublié ?';
$Definition['Full Site'] = 'Site complet';

$Definition['Gender'] = 'Sexe';
$Definition['Go'] = 'Ok';
$Definition['GuestModule.Message'] = 'Si vous souhaitez rejoindre la communauté, cliquez sur un des boutons ci-dessous.';

$Definition['he'] = 'il';
$Definition['his'] = 'sa';
$Definition['Howdy, Stranger!'] = 'Bienvenue dans la Communauté !';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="%s">conditions d\'utilisation du forum</a>.';
$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">terms of service</a>';
$Definition['I remember now!'] = 'Je m\'en souviens maintenant !';
$Definition['In this Conversation'] = 'Dans cette conversation';
$Definition['Inbox'] = 'Boîte de Réception';
$Definition['Internal'] = 'Interne';
$Definition['Invitation Code'] = 'Code d\'Invitation';
$Definition['InvitationCode'] = 'Code d\'Invitation';
$Definition['Invite'] = 'Inviter';
$Definition['Invited by'] = 'Invité(e) par';

$Definition['J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>.'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>.';
$Definition['J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>';
$Definition['J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>.'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">conditions d\'utilisation du forum</a>.';
$Definition['Joined'] = 'Inscrit le';

$Definition['Keep me signed in'] = 'Se souvenir de moi';

$Definition['Last Active'] = 'Activité';
$Definition['Last IP'] = 'Dernière IP';
$Definition['Le Nom d\'Utilisateur ne peut contenir que des lettres, des chiffres, des tirets bas (_), et doit contenir entre 3 et 20 caractères de long.'] = 'Le Nom d\'Utilisateur ne peut contenir que des lettres, des chiffres, des tirets bas (_), et doit contenir entre 3 et 20 caractères de long.';

$Definition['Male'] = 'Homme';
$Definition['message'] = 'message';
$Definition['Most recent by %1$s'] = 'Dernier message par %1$s';
$Definition['My Bookmarks'] = 'Mes Favoris';
$Definition['My Discussions'] = 'Mes Discussions';
$Definition['My Drafts'] = 'Mes Brouillons';
$Definition['My Invitations'] = 'Mes Invitations';
$Definition['My Preferences'] = 'Paramètres de Notification';

$Definition['n/a'] = 'n/a';
$Definition['Name'] = 'Nom';
$Definition['Name Unavailable'] = 'Ce nom est déjà utilisé par une autre personne.';
$Definition['New Password'] = 'Nouveau Mot de passe';
$Definition['No discussions were found.'] = 'Aucune discussion n\'a été trouvée.';
$Definition['No results for %s.'] = 'Aucun résultat de recherche pour <b>%s</b>.';
$Definition['Not much happening here, yet.'] = 'Pas grand chose ne se passe ici, pour l\'instant.';
$Definition['Notifications'] = 'Notifications';
$Definition['Notify me of private messages.'] = 'M\'avertir quand je reçois un message privé..';
$Definition['Notify me when I am added to private conversations.'] = 'M\'avertir quand je suis ajouté à une conversation privée.';
$Definition['Notify me when people comment on a discussion.'] = 'M\'avertir quand quelqu\'un commente une discussion.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'M\'avertir quand quelqu\'un commente une discussion suivie.';
$Definition['Notify me when people comment on my discussions.'] = 'M\'avertir quand quelqu\'un commente une de mes discussions.';
$Definition['Notify me when people mention me in comments.'] = 'M\'avertir quand quelqu\'un me mentionne dans un commentaire.';
$Definition['Notify me when people mention me in discussion titles.'] = 'M\'avertir quand quelqu\'un me mentionne dans le titre d\'une discussion.';
$Definition['Notify me when people reply to my wall comments.'] = 'M\'avertir quand quelqu\'un répond à mes commentaires sur le mur.';
$Definition['Notify me when people start new discussions.'] = 'M\'avertir quand quelqu\'un ouvre une nouvelle discussion.';
$Definition['Notify me when people write on my wall.'] = 'M\'avertir quand quelqu\'un écrit sur mon mur.';
$Definition['Null Date'] = '-';

$Definition['Okay'] = 'Oui';
$Definition['Old Password'] = 'Ancien mot de passe';
$Definition['On'] = 'Le';
$Definition['Options'] = 'Options';
$Definition['Original'] = 'Original';

$Definition['Partager'] = 'Partager';
$Definition['Password'] = 'Mot de Passe';
$Definition['Passwords don\'t match'] = 'Les mots de passe ne correspondent pas.';
$Definition['Pending'] = 'En attente';
$Definition['permalink'] = 'permalien';
$Definition['Popup'] = 'Popup';
$Definition['Post Comment'] = 'Publier le Commentaire';
$Definition['Post Discussion'] = 'Publier la Discussion';
$Definition['Powered by Vanilla'] = 'Propulsé par Vanilla';
$Definition['Preview'] = 'Aperçu';

$Definition['Recent Activity'] = 'Activité Récente';
$Definition['Recipients'] = 'Destinataires';
$Definition['Register IP'] = 'Adresse IP';
$Definition['Remember me on this computer'] = 'Se souvenir de moi sur cet ordinateur';
$Definition['Remove My Picture'] = 'Supprimer ma photo de profil';
$Definition['Remove Picture'] = 'Supprimer la photo de profil';
$Definition['Reopen'] = 'Rouvrir';
$Definition['Request a new password'] = 'Demander un nouveau mot de passe';
$Definition['Reset my password'] = 'Réinitialiser mon mot de passe';
$Definition['Resetting the password for %s.'] = 'Réinitialisation du mot de passe pour %s.';
$Definition['Roles'] = 'Statuts';

$Definition['Save'] = 'Enregistrer';
$Definition['Save Draft'] = 'Enregistrer le Brouillon';
$Definition['Save Preferences'] = 'Enregistrer les Préférences';
$Definition['Save your password'] = 'Enregistrer votre mot de passe';
$Definition['Search'] = 'Rechercher';
$Definition['Send Again'] = 'Renvoyer';
$Definition['Security Check'] = 'Contrôle de Sécurité';
$Definition['Select an image on your computer (2mb max)'] = 'Choisissez une image sur votre ordinateur (2 Mo max.)';
$Definition['Send %s a Message'] = 'Envoyer un message à %s';
$Definition['Send Message'] = 'Envoyer le message';
$Definition['Sent To'] = 'Envoyée à';
$Definition['Share'] = 'Partager';
$Definition['Sign In'] = 'Se connecter';
$Definition['Sign Out'] = 'Se déconnecter';
$Definition['sign out'] = 'se déconnecter';
$Definition['Sign Up'] = 'Je m\'inscris !';
$Definition['Sink'] = 'Déclasser';
$Definition['somebody'] = 'quelqu\'un';
$Definition['Start a New Conversation'] = 'Nouveau message';
$Definition['Start a New Discussion'] = 'Nouvelle Discussion';
$Definition['Start Conversation'] = 'Poster le Message';
$Definition['Started by %1$s'] = 'Commencée par %1$s';
$Definition['Status'] = 'Statut';

$Definition['TermsOfService'] = 'Conditions d\'Utilisation';
$Definition['TermsOfServiceText'] = "
   <p>En utilisant ce service, vous acceptez de ne pas publier de message qui soit délibérément faux et/ou diffamatoire, inapproprié, abusif, vulgaire, incitant à la haine, insultant, obscène, profane, orienté sexuellement, menaçant, portant atteinte à la liberté d'autrui, ou contraire à la loi. Vous acceptez également de ne pas publier de contenu soumis au droit d'auteur, à moins que celui soit détenu par vous.</p>
   
   <p>Nous nous réservons le droit de révéler votre identité (ou les informations permettant de vous identifier) en cas de plainte ou d'action en justice résultant d'un message que vous avez publié. Nous conservons toutes les adresses IP permettant d'accéder à ce forum.</p>
   
   <p>Les publicités, les chaînes et les sollicitations commerciales sont interdites.</p>
   
   <p>Nous nous réservons le droit de modifier, déplacer ou supprimer tout contenu pour quelque raison que ce soit. Nous nous réservons également le droit de bannir un utilisateur ou de clôturer le compte de n'importe quel utilisateur qui ne respecterait pas les présentes conditions.</p>
   
   <p>Pour participer à la communauté, vous devez avoir 13 ans au minimum.</p>
";
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'La valeur du cryptogramme n\'a pas été recopiée correctement.<br />Veuillez essayer à nouveau.';
$Definition['their'] = 'leur';
$Definition['they'] = 'ils';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Cette image a été redimensionnée pour tenir dans la page. Cliquez pour l\'agrandir.';
$Definition['This user has not commented yet.'] = 'Cet utilisateur n\'a pas encore fait de commentaires.';
$Definition['This user has not made any discussions yet.'] = 'Cet utilisateur n\'a démarré aucune discussion.';
$Definition['Thumbnail'] = 'Miniature';
$Definition['Transport error: %s'] = 'Une erreur fatale est survenue pendant l\'exécution de la requête.<br />Le serveur a renvoyé l\'erreur suivante : %s';

$Definition['Unannounce'] = 'Ne plus annoncer';
$Definition['Unbookmark'] = 'Enlever des favoris';
$Definition['Uninvite'] = 'Ne plus inviter';
$Definition['Unknown'] = 'Inconnu';
$Definition['Unsink'] = 'Reclasser';
$Definition['Upload'] = 'Transférer';
$Definition['Username'] = 'Pseudo';
$Definition['UsernameError'] = 'Le Nom d\'Utilisateur ne peut contenir que des lettres, des chiffres, des tirets bas (_), et doit contenir entre 3 et 20 caractères de long.';

$Definition['ValidateEmail'] = '%s ne semble pas valide.';
$Definition['ValidateMatch'] = 'Le(s) champ(s) %s ne correspondent pas.';
$Definition['ValidateRequired'] = 'Le champ %s est obligatoire.';
$Definition['Visits'] = 'Visites';

$Definition['wall'] = 'mur';
$Definition['Welcome Aboard!'] = 'Bienvenue dans la communauté !';
$Definition['Write a comment'] = 'Commenter';
$Definition['Write Comment'] = 'Écrire un Commentaire';
$Definition['Write something about yourself...'] = 'Écrivez quelque chose à propos de vous...';

$Definition['you'] = 'vous';
$Definition['You'] = 'Vous';
$Definition['You are already registered.'] = 'Vous êtes déjà enregistré.';
$Definition['You are attempting to sign out of Vanilla. Are you sure you want to %s?'] = 'Vous tentez de vous déconnecter du forum. Êtes-vous sûr de vouloir %s?';
$Definition['You are previewing the %s theme.'] = 'Vous visualisez un aperçu du thème %s.';
$Definition['You do not have any conversations.'] = 'Votre boîte de réception ne contient aucun message.';
$Definition['You do not have any notifications yet.'] = 'Vous n\'avez aucune notification pour l\'instant.';
$Definition['You must agree to the terms of service.'] = 'Vous devez accepter les conditions d\'utilisation du forum.';
$Definition['You must provide a comment.'] = 'Vous devez écrire un commentaire.';
$Definition['You need to confirm your email address.'] = 'Vous devez confirmer votre adresse email. Cliquez <a href="{/entry/emailconfirmrequest,url}">ici</a> pour renvoyer la demande de confirmation par email.';
$Definition['your'] = 'votre';
$Definition['Your new password is invalid'] = 'Votre nouveau mot de passe est invalide';
$Definition['Your passwords did not match.'] = 'Les mots de passe que vous avez entré ne correspondent pas.';
$Definition['Your preferences have been saved.'] = 'Vos préférences ont été enregistrées.';
