<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2012-03-27 12:27:38 **/


$Definition['&larr; All Discussions'] = '&larr; Toutes les Discussions';

$Definition['%s and you'] = 'Entre %s et vous';
$Definition['%s comment'] = '%s commentaire';
$Definition['%s comments'] = '%s commentaires';
$Definition['%s discussions'] = '%s discussions';
$Definition['%s message'] = '%s message';
$Definition['%s new'] = '%s nouveau';
$Definition['%s New'] = '%s Nouveau';
$Definition['%s New Plural'] = '%s nouveaux';

$Definition['1 message'] = '1 message';

$Definition['(less)'] = '(moins)';
$Definition['(more)'] = '(plus)';

$Definition['[%1$s] %2$s'] = '[%1$s] %2$s';
$Definition['[%s] Invitation'] = '[%s] Invitation';
$Definition['[%1$s] Membership Approved'] = '[%1$s] Candidature approuvée';

$Definition['[%s] Welcome Aboard!'] = '[%s] Bienvenue dans la Communauté !';

$Definition['[%s] Password Reset'] = 'Réinitialisation du mot de passe';          // Email title  
$Definition['[%s] Confirm Your Email Address'] = 'Activer votre abonnement sur %s';
$Definition['[%1$s] Membership Approved'] = 'Bienvenue sur les forums de %1$s';        
$Definition['[%s] Welcome Aboard!'] = '[%s] vous souhaite la bievenue' ;

$Definition['<General Error>'] = '<Erreur Générale>';

$Definition['About'] = 'À propos…';
$Definition['Activity'] = 'Activité';
$Definition['Activity.Comment'] = 'Commenter';

$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s a envoyé un %8$s à %3$s.';   
$Definition['Activity.ConversationMessage.FullHeadline.You.His'] = '%1$s lui avez envoyé un %8$s.';  
$Definition['Activity.ConversationMessage.FullHeadline.You.Somebody'] = '%1$s avez envoyé un %8$s à %3$s.';
$Definition['Activity.ConversationMessage.FullHeadline.He.You'] = '%1$s %3$s a envoyé un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline.Somebody.You'] = '%1$s %3$s a envoyé un %8$s.';

$Definition['Activity.Delete'] = 'Supprimer';

$Definition['Activity.Join.FullHeadline'] = '%1$s a rejoint la communauté.';  
$Definition['Activity.Join.FullHeadline.You'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s s\'est inscrit.';      
$Definition['Activity.Join.ProfileHeadline.You'] = '%1$s vous êtes inscrit.';

$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s a approuvé l\'inscription %4$s.'; 
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s avez commencé une %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s a commencé une %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s a changé %6$s photo de profil.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s a changé %6$s Photo de profil.';
$Definition['Add People to this Conversation'] = 'Ajouter des personnes…';
$Definition['All Categories'] = 'Toutes les Catégories';
$Definition['All Discussions'] = 'Toutes les Discussions';
$Definition['Allow other members to see your email?'] = 'Autoriser les autres membres à voir mon adresse email ?';
$Definition['Apply for Membership'] = 'Devenir membre';
$Definition['Are you sure you want to do that?'] = 'Êtes-vous sûr de vouloir faire cela ?';
$Definition['at'] = 'at';

$Definition['Body'] = 'Contenu';

$Definition['Cancel'] = 'Annuler';
$Definition['Categories'] = 'Catégories';
$Definition['CategoriesShowFollowed'] = 'Afficher uniquement les catégories que vous suivez.';
$Definition['CategoriesShowUnfollowed'] = 'Afficher les catégories non suivies';
$Definition['CategoriesViewingFollowed'] = 'Seules les catégories que vous suivez sont actuellement visibles.';
$Definition['CategoriesViewingAll'] = 'Toutes les catégories sont affichées.';
$Definition['Category Management'] = 'Gestion des Catégories';
$Definition['Change My Password'] = 'Modifier mon Mot de passe';
$Definition['Change My Picture'] = 'Modifier ma Photo de profil';
$Definition['Change Password'] = 'Modifier le Mot de passe';
$Definition['Closed'] = 'Fermé';
$Definition['Comment'] = 'Commenter';
$Definition['Comments'] = 'Commentaires';
$Definition['Confirm'] = 'Confirmer';
$Definition['Confirm Password'] = 'Confirmer le Mot de passe';
$Definition['Create One.'] = 'Je m\'inscris';

$Definition['Dashboard'] = 'Tableau de bord';
$Definition['Date.DefaultDayFormat'] = '%e %B';
$Definition['Date.DefaultTimeFormat'] = '%k:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete Conversation'] = 'Supprimer la conversation';
$Definition['discussion'] = 'discussion';
$Definition['Discussions'] = 'Discussions';
$Definition['Don\'t have an account? %s'] = 'Pas encore inscrit ? %s';
$Definition['dot'] = 'dot';

$Definition['Edit My Account'] = 'Paramètres du Compte';
$Definition['Email'] = 'Email';
$Definition['Email/Username'] = 'Email / Nom d\'Utilisateur';
$Definition['Enter your Email address or username'] = 'Entrez votre adresse Email<br />ou votre Nom d\'Utilisateur';
$Definition['ErrorCredentials'] = 'Désolé, aucun compte n\'est associé à l\'adresse email et au mot de passe que vous avez entrés.';

$Definition['Female'] = 'Femme';
$Definition['Forgot?'] = '<br /><div style="padding: 6px; margin-bottom: 10px;">Mot de passe oublié ?</div>';

$Definition['Gender'] = 'Sexe';
$Definition['Go'] = 'Ok';
$Definition['GuestModule.Message'] = 'Si vous souhaitez rejoindre la communauté, cliquez sur un des boutons ci-dessous.';

$Definition['he'] = 'il';
$Definition['his'] = 'sa';
$Definition['Howdy, Stranger!'] = 'Bienvenue dans la Communauté !';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="%s">conditions d\'utilisation du forum</a>.';
$Definition['I remember now!'] = 'Je m\'en souviens maintenant !';
$Definition['In this Conversation'] = 'Dans cette conversation';
$Definition['Inbox'] = 'Boîte de Réception';
$Definition['Internal'] = 'Interne';

$Definition['Joined'] = 'Inscription';

$Definition['Keep me signed in'] = 'Se souvenir de moi';

$Definition['Last Active'] = 'Activité';

$Definition['Male'] = 'Homme';
$Definition['Most recent by %1$s'] = 'Dernier message par %1$s';
$Definition['My Preferences'] = 'Préférences de notifications';

$Definition['Name Unavailable'] = 'Ce nom est déjà utilisé par une autre personne.';
$Definition['New Password'] = 'Nouveau Mot de passe';
$Definition['No discussions were found.'] = 'Aucune discussion n\'a été trouvée.';
$Definition['Notifications'] = 'Notifications';

$Definition['Okay'] = 'Oui';
$Definition['Old Password'] = 'Ancien mot de passe';

$Definition['Password'] = 'Mot de Passe';
$Definition['Passwords don\'t match'] = 'Les mots de passe ne correspondent pas.';
$Definition['Powered by Vanilla'] = 'Propulsé par Vanilla';

$Definition['Recent Activity'] = 'Activité Récente';
$Definition['Recipients'] = 'Destinataires';
$Definition['RecipientUserID'] = 'Destinataire';
$Definition['Remember me on this computer'] = 'Se souvenir de moi sur cet ordinateur';
$Definition['Request a new password'] = 'Demander un nouveau mot de passe';
$Definition['Roles'] = 'Statuts';

$Definition['Se souvenir de moi'] = 'Se souvenir de moi';
$Definition['Search'] = 'Rechercher';
$Definition['Security Check'] = 'Contrôle de Sécurité';
$Definition['Send Message'] = 'Envoyer le message';
$Definition['Share'] = 'Partager';
$Definition['Sign In'] = 'Se connecter';
$Definition['Sign Out'] = 'Se déconnecter';
$Definition['Sign Up'] = 'Je m\'inscris !';
$Definition['somebody'] = 'quelqu\'un';
$Definition['Start a New Conversation'] = '+ Nouveau message';
$Definition['Start a New Discussion'] = '+ Nouvelle Discussion';
$Definition['Started by %1$s'] = 'Commencée par %1$s';

$Definition['TermsOfService'] = 'Conditions d\'utilisation';
$Definition['TermsOfServiceText'] = "
   <p>En utilisant ce service, vous acceptez de ne pas publier de message qui soit délibérément faux et/ou diffamatoire, inapproprié, abusif, vulgaire, incitant à la haine, insultant, obscène, profane, orienté sexuellement, menaçant, portant atteinte à la liberté d'autrui, ou contraire à la loi. Vous acceptez également de ne pas publier de contenu soumis au droit d'auteur, à moins que celui soit détenu par vous.</p>
   
   <p>Nous nous réservons le droit de révéler votre identité (ou les informations permettant de vous identifier) en cas de plainte ou d'action en justice résultant d'un message que vous avez publié. Nous conservons toutes les adresses IP permettant d'accéder à ce forum.</p>
   
   <p>Les publicités, les chaînes et les sollicitations commerciales sont interdites.</p>
   
   <p>Nous nous réservons le droit de modifier, déplacer ou supprimer tout contenu pour quelque raison que ce soit. Nous nous réservons également le droit de bannir un utilisateur ou de clôturer le compte de n'importe quel utilisateur qui ne respecterait pas les présentes conditions.</p>
   
   <p>Pour participer à la communauté, vous devez avoir 13 ans au minimum.</p>
";
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'La valeur du cryptogramme n\'a pas été recopiée correctement.<br />Veuillez essayer à nouveau.';
$Definition['This user has not commented yet.'] = 'Cet utilisateur n\'a pas encore fait de commentaires.';
$Definition['This user has not made any discussions yet.'] = 'Cet utilisateur n\'a démarré aucune discussion.';
$Definition['Transport error: %s'] = 'Une erreur fatale est survenue pendant l\'exécution de la requête.<br />Le serveur a renvoyé l\'erreur suivante : %s';

$Definition['Username'] = 'Pseudo';
$Definition['UsernameError'] = 'Le Nom d\'Utilisateur ne peut contenir que des lettres, des chiffres, des tirets bas (_), et doit contenir entre 3 et 20 caractères de long.';

$Definition['ValidateRequired'] = 'Champs obligatoire requis.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Cochez au moins une des cases requises.';
// THESE ARE RELATED TO VALIDATION FUNCTIONS IN /garden/library/core/validation.functions.php
$Definition['ValidateBanned'] = 'Ce %s n\'est pas autorisé.';
$Definition['ValidateBoolean'] = '%s n\'est pas un booléen valide.';
$Definition['ValidateConnection'] = 'La connexion à la base de données avec les paramètres spécifiés a échoué. Le serveur a indiqué l\'erreur suivante : <code>%s</code>';
$Definition['ValidateDate'] = '%s n\'est pas une date valide.';
$Definition['ValidateDecimal'] = '%s n\'est pas une valeur décimale valide.';
$Definition['ValidateEmail'] = 'L\'adresse %s ne semble pas valide.';
$Definition['ValidateEnum'] = 'La valeur de %s n\'est pas valide.';
$Definition['ValidateInteger'] = 'La valeur de %s n\'est pas un entier valide.';
$Definition['ValidateLength'] = '%1$s est trop long de %2$s caractères.';
$Definition['ValidateMatch'] = 'Le(s) champ(s) %s ne correspondent pas.';
//$Definition['ValidateMinimumAge'] = 'You are too young to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Vous devez sélectionner au moins un %s.';
$Definition['ValidateRegex'] = '%s ne semble pas avoir un format correct.';
$Definition['ValidateRequired'] = 'Le champ %s est obligatoire.';
$Definition['ValidateRequiredArray'] = 'Vous devez choisir au moins un %s.';
$Definition['ValidateTime'] = '%s n\'est pas une référence horaire valide.';
$Definition['ValidateTimestamp'] = '%s n\'est pas un timestamp valide.';
$Definition['ValidateUrlStringRelaxed'] = 'Le champ %s ne peut contenir de caractères barre oblique, guillemet ou étiquette.';
$Definition['ValidateUsername'] = 'Les noms d\'utilisateurs doivent comporter entre 3 et 20 caractères parmis les lettres, les chiffres et le souligné.';
$Definition['ValidateVersion'] = 'Le champ %s n\'est pas un numéro de version valide. Consulter la documentation de la fonction PHP php version_compare() pour des exemples valides.';

$Definition['Visits'] = 'Visites';

$Definition['wall'] = 'mur';
$Definition['Write a comment'] = 'Commenter';
$Definition['Write something about yourself...'] = 'Écrivez quelque chose à propos de vous...';

$Definition['You'] = 'Vous';
$Definition['You are previewing the %s theme.'] = 'Vous visualisez un aperçu du thème %s.';
$Definition['You do not have any conversations.'] = 'Votre boîte de réception ne contient aucun message.';
$Definition['You do not have any notifications yet.'] = 'Vous n\'avez aucune notification pour l\'instant.';
$Definition['You must provide a comment.'] = 'Vous devez écrire un commentaire.';
$Definition['You must agree to the terms of service.'] = 'Vous devez accepter les conditions d\'utilisation du forum.';
$Definition['You need to confirm your email address.'] = 'Vous devez confirmer votre adresse email. Cliquez <a href="{/entry/emailconfirmrequest,url}">ici</a> pour renvoyer la demande de confirmation par email.';
$Definition['your'] = 'votre';